# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x0b\x66lightcache\"&\n\x11InitFlightRequest\x12\x11\n\tall_seats\x18\x01 \x03(\t\"\'\n\x11\x46reeSeatsResponse\x12\x12\n\nfree_seats\x18\x01 \x03(\t\"2\n\x0f\x42ookSeatRequest\x12\x0c\n\x04seat\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\"\n\x10\x42ookSeatResponse\x12\x0e\n\x06\x62ooked\x18\x01 \x01(\x08\"\'\n\x12GetBookingResponse\x12\x11\n\tclient_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITFLIGHTREQUEST']._serialized_start=29
  _globals['_INITFLIGHTREQUEST']._serialized_end=67
  _globals['_FREESEATSRESPONSE']._serialized_start=69
  _globals['_FREESEATSRESPONSE']._serialized_end=108
  _globals['_BOOKSEATREQUEST']._serialized_start=110
  _globals['_BOOKSEATREQUEST']._serialized_end=160
  _globals['_BOOKSEATRESPONSE']._serialized_start=162
  _globals['_BOOKSEATRESPONSE']._serialized_end=196
  _globals['_GETBOOKINGRESPONSE']._serialized_start=198
  _globals['_GETBOOKINGRESPONSE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
