# docker-compose.test.yml (macOS / Windows)
services:
  tests:
    build:
      context: .
      dockerfile: tests/redis/Dockerfile.test
    # Do NOT use network_mode: "host" here.
    # Instead, rely on host.docker.internal to reach the host machine.
    environment:
      REDIS_URL: "redis://host.docker.internal:6379/0"
      GRPC_TARGET: "host.docker.internal:5000"
    # Optionally mount code so you don’t rebuild on every change:
    volumes:
      - ./:/usr/src/app
