apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_API_BASE
              value: http://backend:1919
            - name: redis_service
              value: http://redis-service:5000
          image: gcr.io/cs144proj/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
