apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    networking.gke.io/load-balancer-ip-address: 34.8.72.41  # optional if you reserved static IP
  labels:
    io.kompose.service: frontend
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
