name: Deploy to GKE

on:
  push:
    branches:
      - main  # or your deploy branch
    workflow_dispatch:


jobs:
  deploy:
    name: Build, push, deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use GCR
      run: gcloud auth configure-docker

    # --- Build and push backend ---
    - name: Build backend image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest ./airline-checkin-app/server

    - name: Push backend image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest

    # --- Build and push frontend ---
    - name: Build frontend image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest ./airline-checkin-app/frontend

    - name: Push frontend image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

    # --- Build and push redis-service ---
    - name: Build redis-service image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/redis-service:latest ./airline-checkin-app/redis

    - name: Push redis-service image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/redis-service:latest

    # --- Deploy to GKE ---
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials cs144 --region us-west1

    - name: Deploy to GKE
      run: |
        kubectl apply -f airline-checkin-app/backend-deployment.yaml
        kubectl apply -f airline-checkin-app/frontend-deployment.yaml
        kubectl apply -f airline-checkin-app/redis-service-deployment.yaml
        kubectl apply -f airline-checkin-app/redis-deployment.yaml
        kubectl apply -f airline-checkin-app/backend-service.yaml
        kubectl apply -f airline-checkin-app/frontend-service.yaml
        kubectl apply -f airline-checkin-app/redis-service-service.yaml
        kubectl apply -f airline-checkin-app/redis-service.yaml
        kubectl apply -f airline-checkin-app/redis.yaml
