name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: Build, Push, and Deploy to GKE
    runs-on: ubuntu-latest

    # Set the working directory for all 'run' steps to your project folder
    defaults:
      run:
        working-directory: ./airline-checkin-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Use auth@v2 → this replaces your manual activate-service-account step
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use GCR
      run: gcloud auth configure-docker gcr.io --quiet

    # This step is correct: create serviceAccountKey.json for backend build
    - name: Create Service Account Key File for Build
      run: echo '${{ secrets.GCP_SA_KEY }}' > server/serviceAccountKey.json

    # Set the Artifact Registry path as an environment variable for easy reuse
    - name: Set image repository variable
      run: echo "IMAGE_REPO=us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airline-app-repo" >> $GITHUB_ENV

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/backend:latest -f server/Dockerfile .
        docker push ${{ env.IMAGE_REPO }}/backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/frontend:latest -f frontend/Dockerfile .
        docker push ${{ env.IMAGE_REPO }}/frontend:latest
        
    - name: Build and Push Redis Service Image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/redis-service:latest -f redis/Dockerfile .
        docker push ${{ env.IMAGE_REPO }}/redis-service:latest

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials cs144 --region us-west1

    - name: Deploy to GKE
      # The paths are now correct because of the `working-directory` setting above
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f redis-deployment.yaml
        kubectl apply -f redis-service-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-service.yaml
        kubectl apply -f redis-service.yaml
