name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: Build, Push, and Deploy to GKE
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./airline-checkin-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

    - name: Create Service Account Key File
      run: echo '${{ secrets.GCP_SA_KEY }}' > server/serviceAccountKey.json

    - name: Set Image Repo Variable
      run: echo "IMAGE_REPO=us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airline-app-repo" >> $GITHUB_ENV

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/backend:latest -f server/Dockerfile .
        docker push ${{ env.IMAGE_REPO }}/backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/frontend:latest -f frontend/Dockerfile frontend/
        docker push ${{ env.IMAGE_REPO }}/frontend:latest
        
    - name: Build and Push Redis Service Image
      working-directory: airline-checkin-app
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/redis-service:latest -f redis/Dockerfile .
        docker push ${{ env.IMAGE_REPO }}/redis-service:latest

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials cs144 --region us-west1

    - name: Update Kubernetes Manifests
      run: |
        sed -i 's|gcr.io/cs144proj/backend:latest|${{ env.IMAGE_REPO }}/backend:latest|g' backend-deployment.yaml
        sed -i 's|gcr.io/cs144proj/frontend:latest|${{ env.IMAGE_REPO }}/frontend:latest|g' frontend-deployment.yaml
        sed -i 's|gcr.io/cs144proj/redis-service:latest|${{ env.IMAGE_REPO }}/redis-service:latest|g' redis-service-deployment.yaml

    - name: Deploy to GKE
      run: |
        # Apply Deployments First
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f redis-deployment.yaml
        kubectl apply -f redis-service-deployment.yaml

        # Apply Services Next
        kubectl apply -f backend-service.yaml
        kubectl apply -f redis-service.yaml

    - name: Force rollout of frontend Deployment
      run: kubectl rollout restart deployment frontend

    - name: Force rollout of backend Deployment
      run: kubectl rollout restart deployment backend

    - name: Force rollout of redis Deployment
      run: kubectl rollout restart deployment redis
